version: '1.0'
services:
  db:
    image: mysql:8.0.31
    ports:
      - '3306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: petya
      MYSQL_PASSWORD: qwerty123
      MYSQL_DATABASE: app